
TOP_MODULE=fpio_top

FAMILY:="Cyclone V"
DEVICE:=5CSXFC6D6F31C8ES

# QPF_FLAGS += +define+ALTERA_DEVICE_FAMILY=\"Cyclone V\"

# DATAFILES += $(BUILD_DIR)/rom.hex

# SIM_PRE_TARGETS += mk_rom

include $(SYNTHSCRIPTS_DIR)/mkfiles/common_synth.mk

# $(BUILD_DIR)/rom.img : mk_rom

#.phony: mk_rom
#$(BUILD_DIR)/%.hex:
#	$(MAKE) -f $(SYNTH_DIR)/scripts/embedded_sw.mk $@


